/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    }

    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("me.clip:placeholderapi:2.11.3")
    compileOnly("io.papermc.paper:paper-api:1.20.1-R0.1-SNAPSHOT")
    compileOnly("net.md-5:bungeecord-chat:1.16-R0.4")
    compileOnly("com.mojang:datafixerupper:4.0.26")
    compileOnly("com.mojang:brigadier:1.0.18")
    compileOnly("com.mojang:javabridge:1.2.24")
    compileOnly("com.mojang:authlib:3.2.38")
    compileOnly("com.google.code.gson:gson:2.8.9")
    compileOnly("io.netty:netty-all:4.1.86.Final")
    compileOnly("it.unimi.dsi:fastutil:8.5.6")
    compileOnly("com.google.collections:google-collections:1.0")
    compileOnly("net.kyori:adventure-api:4.14.0")
}

group = "FartherViewDistance"
version = "9.7.7"
description = "FartherViewDistance"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
