name: FartherViewDistance
version: '${version}'
main: com.jokni.fartherviewdistance.code.ChunkIndex
api-version: '1.21'
website: "https://github.com/DaJokni/FartherViewDistance"
description: "Plugin that can increase the view distance of a player on a server."
authors:
  - "xuancat0208"
  - "DaJokni"