name: FartherViewDistance
version: '9.12.0'
main: xuan.cat.fartherviewdistance.code.ChunkIndex
api-version: '1.20'
authors:
  - "xuancat0208"
  - "DaJokni"
dependencies:
  server:
    PlaceholderAPI:
      load: AFTER
      required: false