name: FartherViewDistance
version: 9.11.0
main: xuan.cat.fartherviewdistance.code.ChunkIndex
api-version: 1.20
softdepend: [PlaceholderAPI]
authors: [xuancat0208]
commands:
  viewdistance:
    usage: op
