name: FartherViewDistance
version: ${project.version}
main: xuan.cat.fartherviewdistance.code.ChunkIndex
api-version: 1.20
softdepend: [PlaceholderAPI]
authors: [xuancat0208]
commands:
  viewdistance:
    usage: op
